config/routes.rb
Rails.application.routes.draw do

  get '/buy_shoe',to: 'buy#index'
  get '/buy_purse',to: 'buy#index1'
  get '/buy_hood',to: 'buy#index2'
  get '/buy_hood1',to: 'buy#index3'
  get 'homelogged_in/index'
  get 'detail_logged/index'
  get '/detail_no_login', to: 'detail_no_login#index'
  get '/detail_no_login2', to: 'detail_no_login#index2'
  get '/detail_no_login3', to: 'detail_no_login#index3'
  get '/detail_no_login4', to: 'detail_no_login#index4'
  get '/detail_logged', to: 'detail_logged#index'
  get '/detail_logged2', to: 'detail_logged#index2'
  get '/detail_logged3', to: 'detail_logged#index3'
  get '/detail_logged4', to: 'detail_logged#index4'
  get '/welcome', to: 'welcome#index'
  get '/homelogged_in', to: 'homelogged_in#index'
  get '/register', to: 'register#index'



  resources :orders
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  get '/home',  to: 'users#home'
  get '/about', to: 'users#about'
  get '/userorder', to: 'orders#userorder'
  get '/neworder', to: 'orders#new'
  get '/neworderfalse', to: 'sessions#new'
  root 'users#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<div class="container">
    <div class="site-header">
        <div class="site-header-logo">
            <image src="/images/logo.png" width="350" height="100"></image>
        </div>
        <div class="site-header-nav">
            <ul>
                <li><a><%= link_to "Home" , home_path %></a></li>

                <% if current_user %>
                <% else %>
                <li><a><%= link_to "Sign Up", signup_path %></a></li>
                <li><a><%= link_to "Log In", login_path %></a></li>
                <% end %>

                <li><a><%= link_to "About" , about_path %></a></li>

                <% if current_user%>
                <% if current_user.email == 'admin'%>
                <li><a><%= link_to "Admin Order", orders_path %></a></li>
                <li><a><%= link_to "Log Out", logout_path %></a></li>
                <li><a><%= link_to "Edit", edit_user_path(current_user) %></a></li>
                Logged in as
                <%= current_user.email %>
                <% else %>
                <li><a><%= link_to "User Order", userorder_path %></a></li>
                <li><a><%= link_to "Log Out", logout_path %></a></li>
                <li><a><%= link_to "Edit", edit_user_path(current_user) %></a></li>
                Logged in as
                <%= current_user.email %>
                <% end %>
                <% end %>
            </ul>
        </div>
    </div>


</div>

<head>
    <title>Preorder24</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Hind&display=swap" rel="stylesheet">
    <style>
    	body{
            font-family: 'Hind', sans-serif;
            margin: 0;
            color:gold;
    	}

        
    </style>
</head>
<body>
    <%= yield %>
</body>

<div class="site-footer">
    <p style="text-align: center">&copy; <b>2019 - CN340 SOFTWARE ENGINEERING</b></p>
</div>

</html>